### PR TITLE
Update jacoco with Java 15 support

### PR DESCRIPTION
**Pull request by arturbosch**

### CODE REVIEW

**Review by schalkms — APPROVED** [review]

**Comment by arturbosch** [comment]
Windows is soo slow, should we drop testing latest Java on Windows maybe?

**Comment by BraisGabin** [comment]
> Windows is soo slow, should we drop testing latest Java on Windows maybe? Or just 8 and latest ...

Right now the matrix is fully parallel, will we get a performance boost doing that?

**Comment by arturbosch** [comment]
Linux ran in ~9-15m, Windows in ~22-30m. 8 minutes more for Java14 than Java8.
When doing a release I often have to wait for 1-2 Windows job when collecting some smaller PRs.
But maybe it is not the default CI case but a special one - sometimes for me.

**Comment by BraisGabin** [comment]
That have sense.

**Pull request merged**
