### PR TITLE
Replace lock with stale bot

### PR DESCRIPTION
**Pull request by cortinico**
I'm removing the `lock.yaml` file for the bot which is not working anymore (do we need it still?). Given that it was a 3rd party tool, I've moved to a 1st party Github actions that is doing something similar: marking issues inactive since more than 180 days (should I change it)?

Happy to tune it if it doesn't fit our needs.

### CODE REVIEW

**Review by chao2zhang — APPROVED** [review]
In my opinion, this number should be close to 2 release cycles - My justification is that in case we ask the PR author to hold off until the next release is published.

It feels like 180 days is on the conservative side, but this looks reasonable to me.

**Comment by 3flex** [comment]
> It feels like 180 days is on the conservative side

Agree - maybe 90 days? Or perhaps 90 days for PRs and 180 days for issues. PRs shouldn't hang around open for a long time (and yes, I realise I'm guilty of doing this!)

Also does this lock issues/PRs if they're stale & closed, or does it just close them? If they're just closed then 👍 since they can always be reopened by the reporter later if they still want to work on it or the issue is still something they care about.

**Comment by cortinico** [comment]
> Also does this lock issues/PRs if they're stale & closed, or does it just close them?

This will just close the issues. 

> Agree - maybe 90 days?

Updating to 90

**Comment by 3flex** [comment]
Just noticed the message posted when an issue or PR is marked as stale says that the Stale label should be removed, but only those with write access on the repo can do that.

Better to just say that a comment should be posted.

**Review by 3flex — APPROVED** [review]

**Comment by 3flex** [comment]
I just commented on an issue marked stale by the new bot but the Stale label wasn't removed... Does the config need changes?

See #3866

**Comment by cortinico** [comment]
> I just commented on an issue marked stale by the new bot but the Stale label wasn't removed... Does the config need changes?

Not really. The action runs daily so it will be updated tonight. The doc says:

> If an update/comment occur on stale issues or pull requests, the stale label will be removed and the timer will restart

**Comment by BraisGabin** [comment]
I have "internal conflicts" with this. I agree that we have far too much issues opened and it's difficult to focus in the important things. But do we want to auto-close valid but low-priority issues?

**Comment by cortinico** [comment]
We can add some labels that will be filtered out by the action. For instance maybe the "help wanted" labelled should never get stale. Or we can create a "never get stale" label that triggers this.

**Comment by BraisGabin** [comment]
Oh, that would be great. We do need to refactor our tags

**Pull request merged**
