### PR TITLE
Improve how we create Fakes of `SetupContext`

### PR DESCRIPTION
**Pull request by BraisGabin**

### CODE REVIEW

**Comment by BraisGabin** [comment]
@detekt/maintainers a review here would be great. This one should be easy/non controversial and will unlock more interesting PRs.

**Review by schalkms — COMMENTED** [review]
Isn’t this *just* a refactoring by moving code around in the test package? What’s really getting improved here?

**Comment by BraisGabin** [comment]
Yes, this is a refactor. It improves the code for two reasons: 

- The tests are less verbose and more focused on what you are tesring.
- make the tests less fragile. If you add a new property `SetupContext` the tests that doesn't care about that new property doesn't need to be changed now. And that's exactly what happen in the next PRs.

(Sorry this should be written when I created this PR)

**Review by schalkms — APPROVED** [review]
Thanks for the explanation! Approved ✅

**Pull request merged**
