### PR TITLE
Less verbose tests

### PR DESCRIPTION
**Pull request by BraisGabin**
Make the compiler-plugin tests less verbose:

Previusly:

```
CompilerTest > with a source file that contains violations() STANDARD_OUT
    logging: Created temporary working directory at /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation8875387757232399014
    logging: No services were given. Not running kapt steps.
    v: Using Kotlin home directory <no_path>
    v: Using JDK home directory /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
    v: Exception on loading scripting plugin: java.lang.ClassNotFoundException: org.jetbrains.kotlin.scripting.compiler.plugin.ScriptingCompilerConfigurationComponentRegistrar
    v: Scripting plugin will not be loaded: not all required jars are present in the classpath (missing files: [./kotlin-scripting-compiler.jar, ./kotlin-scripting-compiler-impl.jar, ./kotlin-scripting-common.jar, ./kotlin-scripting-jvm.jar])
    v: Using JVM IR backend
    v: Configuring the compilation environment
    v: Loading modules: [java.se, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.incubator.foreign, jdk.incubator.vector, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.jfr, jdk.net, jdk.nio.mapmode, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.unsupported.desktop, jdk.xml.dom, java.base, java.compiler, java.datatransfer, java.desktop, java.xml, java.instrument, java.logging, java.management, java.management.rmi, java.rmi, java.naming, java.net.http, java.prefs, java.scripting, java.security.jgss, java.security.sasl, java.sql, java.transaction.xa, java.sql.rowset, java.xml.crypto, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.le, jdk.internal.opt]
    v: Output:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation2522115982881707435/classes/KClass.class
    Sources:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation2522115982881707435/sources/KClass.kt
    v: Output:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation2522115982881707435/classes/META-INF/main.kotlin_module
    Sources:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation2522115982881707435/sources/KClass.kt
    i: Running detekt on module '<main>'
    i: /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation2522115982881707435/sources/KClass.kt:6:2: The file KClass.kt is not ending with a new line. [NewLineAtEndOfFile]
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation2522115982881707435/sources/KClass.kt:3:17: This expression contains a magic number. Consider defining it to a well named constant. [MagicNumber]
    i:
    i: 1 files analyzed
    i: style: 2 findings found.
    i: Success?: false
    w: Analysis failed with 2 issues.
    w: file:///var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation2522115982881707435/sources/KClass.kt:6:2 NewLineAtEndOfFile: The file KClass.kt is not ending with a new line.
    w: file:///var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation2522115982881707435/sources/KClass.kt:3:17 MagicNumber: This expression contains a magic number. Consider defining it to a well named constant.

CompilerTest > with a source file that contains local suppression() STANDARD_OUT
    logging: Created temporary working directory at /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation14666694828103075006
    logging: No services were given. Not running kapt steps.
    v: Using Kotlin home directory <no_path>
    v: Using JDK home directory /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
    v: Exception on loading scripting plugin: java.lang.ClassNotFoundException: org.jetbrains.kotlin.scripting.compiler.plugin.ScriptingCompilerConfigurationComponentRegistrar
    v: Scripting plugin will not be loaded: not all required jars are present in the classpath (missing files: [./kotlin-scripting-compiler.jar, ./kotlin-scripting-compiler-impl.jar, ./kotlin-scripting-common.jar, ./kotlin-scripting-jvm.jar])
    v: Using JVM IR backend
    v: Configuring the compilation environment
    v: Loading modules: [java.se, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.incubator.foreign, jdk.incubator.vector, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.jfr, jdk.net, jdk.nio.mapmode, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.unsupported.desktop, jdk.xml.dom, java.base, java.compiler, java.datatransfer, java.desktop, java.xml, java.instrument, java.logging, java.management, java.management.rmi, java.rmi, java.naming, java.net.http, java.prefs, java.scripting, java.security.jgss, java.security.sasl, java.sql, java.transaction.xa, java.sql.rowset, java.xml.crypto, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.le, jdk.internal.opt]
    v: Output:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation14666694828103075006/classes/KClass.class
    Sources:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation14666694828103075006/sources/KClass.kt
    v: Output:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation14666694828103075006/classes/META-INF/main.kotlin_module
    Sources:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation14666694828103075006/sources/KClass.kt
    i: Running detekt on module '<main>'
    i: 1 files analyzed
    i: Success?: true

CompilerTest > with a source file that does not contain violations() STANDARD_OUT
    logging: Created temporary working directory at /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation6392519861498146915
    logging: No services were given. Not running kapt steps.
    v: Using Kotlin home directory <no_path>
    v: Using JDK home directory /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
    v: Exception on loading scripting plugin: java.lang.ClassNotFoundException: org.jetbrains.kotlin.scripting.compiler.plugin.ScriptingCompilerConfigurationComponentRegistrar
    v: Scripting plugin will not be loaded: not all required jars are present in the classpath (missing files: [./kotlin-scripting-compiler.jar, ./kotlin-scripting-compiler-impl.jar, ./kotlin-scripting-common.jar, ./kotlin-scripting-jvm.jar])
    v: Using JVM IR backend
    v: Configuring the compilation environment
    v: Loading modules: [java.se, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.incubator.foreign, jdk.incubator.vector, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.jfr, jdk.net, jdk.nio.mapmode, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.unsupported.desktop, jdk.xml.dom, java.base, java.compiler, java.datatransfer, java.desktop, java.xml, java.instrument, java.logging, java.management, java.management.rmi, java.rmi, java.naming, java.net.http, java.prefs, java.scripting, java.security.jgss, java.security.sasl, java.sql, java.transaction.xa, java.sql.rowset, java.xml.crypto, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.le, jdk.internal.opt]
    v: Output:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation6392519861498146915/classes/KClass.class
    Sources:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation6392519861498146915/sources/KClass.kt
    v: Output:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation6392519861498146915/classes/META-INF/main.kotlin_module
    Sources:
    /var/folders/_9/ntvzf7jd6y30cr9rxs154vl996qbgx/T/Kotlin-Compilation6392519861498146915/sources/KClass.kt
    i: Running detekt on module '<main>'
    i: 1 files analyzed
    i: Success?: true
```

Now: 
```
```

### CODE REVIEW

**Comment by 3flex** [comment]
Agree this info is of little value when tests pass.

What do we see on failure when verbose mode is off?

**Comment by BraisGabin** [comment]
> Agree this info is of little value when tests pass.
> 
> What do we see on failure when verbose mode is off?

Really good point! Fixed.

**Comment by marschwar** [comment]
I don't like the output in case of a failure. For example if `assertThat(...).passDetekt()` fails, the following output is printed
```
i: Running detekt on module '<main>'
i: /tmp/Kotlin-Compilation17645104193298026506/sources/KClass.kt:3:17: This expression contains a magic number. Consider defining it to a well named constant. [MagicNumber]

i: 

i: 1 files analyzed
i: style: 1 findings found.
i: Success?: false
w: Analysis failed with 1 issues.
w: file:///tmp/Kotlin-Compilation17645104193298026506/sources/KClass.kt:3:17 MagicNumber: This expression contains a magic number. Consider defining it to a well named constant.

Expected detekt to finish with success status: true but was false.
i: Running detekt on module '<main>'
i: /tmp/Kotlin-Compilation17645104193298026506/sources/KClass.kt:3:17: This expression contains a magic number. Consider defining it to a well named constant. [MagicNumber]

i: 

i: 1 files analyzed
i: style: 1 findings found.
i: Success?: false
w: Analysis failed with 1 issues.
w: file:///tmp/Kotlin-Compilation17645104193298026506/sources/KClass.kt:3:17 MagicNumber: This expression contains a magic number. Consider defining it to a well named constant.

Expected :true
Actual   :false
<Click to see difference>

org.opentest4j.AssertionFailedError: Expected detekt to finish with success status: true but was false.
i: Running detekt on module '<main>'
i: /tmp/Kotlin-Compilation17645104193298026506/sources/KClass.kt:3:17: This expression contains a magic number. Consider defining it to a well named constant. [MagicNumber]

i: 

i: 1 files analyzed
i: style: 1 findings found.
i: Success?: false
w: Analysis failed with 1 issues.
w: file:///tmp/Kotlin-Compilation17645104193298026506/sources/KClass.kt:3:17 MagicNumber: This expression contains a magic number. Consider defining it to a well named constant.

	at java.base@17.0.6/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base@17.0.6/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base@17.0.6/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base@17.0.6/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at app//io.github.detekt.compiler.plugin.CompilerTest.with a source file that contains local suppression(CompilerTest.kt:46)
	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.6/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.6/java.util.ArrayList.forEach(ArrayList.java:1511)
```

We could write this instead

```kotlin
info.overridingErrorMessage { 
    "Expected detekt to finish with success status: $expectedStatus but was $status." 
}
objects.assertEqual(info, status, expectedStatus)
```

and receive

```
i: Running detekt on module '<main>'
i: /tmp/Kotlin-Compilation16850713484939223476/sources/KClass.kt:3:17: This expression contains a magic number. Consider defining it to a well named constant. [MagicNumber]

i: 

i: 1 files analyzed
i: style: 1 findings found.
i: Success?: false
w: Analysis failed with 1 issues.
w: file:///tmp/Kotlin-Compilation16850713484939223476/sources/KClass.kt:3:17 MagicNumber: This expression contains a magic number. Consider defining it to a well named constant.

java.lang.AssertionError: Expected detekt to finish with success status: true but was false.
	at app//io.github.detekt.compiler.plugin.util.CompilationAssert.passDetekt(CompilerAssertions.kt:46)
	at app//io.github.detekt.compiler.plugin.util.CompilationAssert.passDetekt$default(CompilerAssertions.kt:37)
	at app//io.github.detekt.compiler.plugin.CompilerTest.with a source file that contains local suppression(CompilerTest.kt:46)
	at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.6/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.6/java.util.ArrayList.forEach(ArrayList.java:1511)

```

**Comment by BraisGabin** [comment]
I don't have experience with this assert library. @marschwar do you want to commit to the pr with those changes?

**Comment by BraisGabin** [comment]
I added a new commit. Now the passing tests are *really* quiet. I didn't change anything related with the failing ones.

**Comment by marschwar** [comment]
I think that is even better now.

Looking into this some more I realized that `failWithActualExpectedAndMessage` and `failWithMessage` are actually quite ok. Nothing to be done there.

Should we turn on verbosity again so they show up in case of failure or do those messages contain no valuable information.

**Comment by BraisGabin** [comment]
The verbosity does nothing at all now that I rewrote the outputStream. So I just removed. And, if you agree, I would lean to merge this. If there are more improvements we can make them on other PRs.

**Review by marschwar — APPROVED** [review]

**Pull request merged**
