### PR TITLE
Make `Entity.ktElement` no nullable

### PR DESCRIPTION
**Pull request by BraisGabin**
There is not a good reason to keep `Entity.ktElement` nullable. It just make the API messier and provide no value.

### CODE REVIEW

**Review by 3flex — DISMISSED** [review]
This might not be a good idea:

1. Not all rule violations relate to a KtElement, for example trailing whitespace (whitespace is represented by a PsiElement)
2. Rule violations like MaxLineLength can include multiple KtElements

I haven't looked into it, but do we actually need to include the KtElement in the Entity at all? A location, signature and location should be enough to report on issues.

**Comment by BraisGabin** [comment]
Rebased to fix conflicts. A review here would be great. This is not a big blocker or anything else but it would be nice to merge it.

**Comment by cortinico** [comment]
CI is really red here @BraisGabin

**Comment by BraisGabin** [comment]
Fixed. The new rule from ktlint always bites be.

**Review by cortinico — APPROVED** [review]

**Pull request merged**
