### PR TITLE
Allow camelCase for top level constant names

### LINKED ISSUE #3147: CamelCase should be accepted for top level constant names
As an alternative to companion object const variable, we can just create top level constants and CamelCase should be accepted too, example:

```
private const val AndroidxSnapshotBuildId = 6911187
```

### PR DESCRIPTION
**Pull request by BraisGabin**
Fix #3147

### CODE REVIEW

**Comment by arturbosch** [comment]
I would really like just to merge f2e5107c005733cd37b6c9071976bbf56e8f6e22 for 1.14.2

**Comment by BraisGabin** [comment]
Done

**Comment by BraisGabin** [comment]
I'm not sure if we should merge this #3147

**Comment by arturbosch** [comment]
@BraisGabin got ya

**Pull request closed without merging**
