### PR TITLE
Remove obsolete api documentation entries

### PR DESCRIPTION
**Pull request by arturbosch**
dokka deleted them.

### CODE REVIEW

**Comment by arturbosch** [comment]
Seems like changing the jdk changes the generated documentation ...

**Review by schalkms — APPROVED** [review]
That’s interesting. Why does another configured JDK version produce a different output?

**Review by BraisGabin — APPROVED** [review]

**Comment by arturbosch** [comment]
Our CI runs with jdk14. Using 14 locally does not change the docs. 
Using jdk11 does.
Should we consider building and verifying the docs with Java11 / always use LTS ?
Which java version do you guys use?
It is indeed a small inconvenience for our contributors.
However no one yet complained about it.

**Comment by BraisGabin** [comment]
I use JDK8. I had this problem in my last 2 PRs but I didn't commit those changes because I readed this PR first.

I couldn't find any related issue in dokka. Should we open one?

**Comment by arturbosch** [comment]
> I use JDK8. I had this problem in my last 2 PRs but I didn't commit those changes because I readed this PR first.
> 
> I couldn't find any related issue in dokka. Should we open one?

Yes, I've opened https://github.com/Kotlin/dokka/issues/1577 for this ,thanks!

**Pull request closed without merging**
