### PR TITLE
Update Gradle to 6.5

### PR DESCRIPTION
**Pull request by cortinico**

### CODE REVIEW

**Comment by BraisGabin** [comment]
Moka, Java 11 and gradle 6.5... They are not friends.

**Comment by arturbosch** [comment]
Hm, OOM looks not good. Need to investigate if its Gradle 6.5 or introduced in #2756 somehow.
The last 2-3 PRs were green though ...

**Comment by cortinico** [comment]
> Hm, OOM looks not good. Need to investigate if its Gradle 6.5 or introduced in #2756 somehow.
> The last 2-3 PRs were green though ...

Seems to be related to Dokka + Java 11 right?

**Comment by arturbosch** [comment]
> > Hm, OOM looks not good. Need to investigate if its Gradle 6.5 or introduced in #2756 somehow.
> > The last 2-3 PRs were green though ...
> 
> Seems to be related to Dokka + Java 11 right?

Right. also found the `detekt-api:dokka`.
Some quick googling and github issues search @ gradle or dokka were unsuccessful here...

**Comment by arturbosch** [comment]
I will close this as we need to wait for the next dokka and Gradle 6.6 will be out soon.

**Pull request closed without merging**
