### PR TITLE
Execute tests in parallel

### PR DESCRIPTION
**Pull request by Goooler**
https://docs.gradle.org/8.0/userguide/performance.html#execute_tests_in_parallel

### CODE REVIEW

**Comment by 3flex** [comment]
I'm not sure why I haven't tried this earlier!

I think we should be a bit less aggressive though and use the suggestion from the Gradle docs which caps forks to half the processor count at most.

**Comment by Goooler** [comment]
I believe we can use `Runtime.getRuntime().availableProcessors()` on CI, which means full cores, there are 2 cores in GHA runners, use `(Runtime.getRuntime().availableProcessors() / 2).takeIf { it > 0 } ?: 1` (result is 1) here seems to be less improvement on CI.

**Comment by Goooler** [comment]
I believe we can use `Runtime.getRuntime().availableProcessors()` on CI, which means full cores, there are 2 cores in GHA runners, use `(Runtime.getRuntime().availableProcessors() / 2).takeIf { it > 0 } ?: 1` (result is 1) here seems to be less improvement on CI.

**Comment by 3flex** [comment]
I was thinking about local builds. Maybe make it conditional on `CI` environment variable to use all cores in CI but not when building locally.

**Review by 3flex — APPROVED** [review]

**Review by schalkms — APPROVED** [review]

**Pull request merged**
