### PR TITLE
Integrated former method for looking up annotation names in AnnotationSuppressor

### PR DESCRIPTION
**Pull request by severn-everett**
Addresses #4355 and #4356

### CODE REVIEW

**Comment by BraisGabin** [comment]
Thanks for the PR! I'm working on something similar here #4368. The problem with the former method is that it didn't work for all the cases as I expose in that PR. I want to create a new class `FullQualifiedNameGuesser` that given a file and a name it provides you with all the possible FullQualifiedNames that it could have (usually it only returns one but it could return mutliple ones). I think that it will be ideal to use the same class to implement both use cases: `AnnotationExcluder` and `AnnotationSuppressor`.

**Comment by BraisGabin** [comment]
To make more clear what I'm talking about this is the WIP `FullQualifiedNameGuesser` class and it's integration with `AnnotationExcluder`: https://github.com/detekt/detekt/compare/AnnotationExcluder..FullQualifiedNameGuesser

**Comment by severn-everett** [comment]
Ok, so should I close this PR?

**Comment by BraisGabin** [comment]
No, don't close it. If that could end up merged this PR could be reworked and, if it's not we can merge directly this.

**Comment by chao2zhang** [comment]
#4368 is merged so this PR should be unblocked.

**Comment by BraisGabin** [comment]
I just launched #4518. Once we have that implemented we can rebase this one and work with `AnnotationExcluder` when we don't have the `BindingContext` and the current implementation when we have it.

**Comment by cortinico** [comment]
What's the timeline here? I'd like to kickoff the `1.20.0-RC1` process and this is pretty high prio to land. If we wish we can release RC1 without this for now, and postpone to RC2. Having it in though would be a major win.

**Comment by BraisGabin** [comment]
I think that as soon as #4518 is merged we can fix this.

**Comment by BraisGabin** [comment]
@severn-everett sorry for the delay. Finally the needed code is merged. Do you want to continue with this using `AnnotationExcluder` for the case when we don't have type solving and keeping the current implementation for when we have type solving?

**Comment by cortinico** [comment]
@BraisGabin how do you feel about taking this over if @severn-everett doesn't have bandwidth? I'd like to include this into a RC1 so we can reiterate on this feature for a RC2 if needed.

**Comment by BraisGabin** [comment]
Sure, I can. I'll try to do it this weekend

**Comment by BraisGabin** [comment]
Closing in favor of #4570

**Pull request closed without merging**
