### PR TITLE
Update dokka to 1.4.10.2

### PR DESCRIPTION
**Pull request by arturbosch**
I guess every new version of dokka will now introduce many changes for us e.g. by changing a link -> every page will get the change.

1. We could wait until dokka 1.4 becomes stable and only update for minor versions.
2. Invest time in making running the dokkaJekyll task only on documentation deploy. I think we do not need to check in the kdoc api or do I miss something? This will result in a different jekyll github-pages setup as this step is fully handled by GitHub for now.

### CODE REVIEW

**Comment by cortinico** [comment]
> 2\. Invest time in making running the dokkaJekyll task only on documentation deploy. I think we do not need to check in the kdoc api or do I miss something? This will result in a different jekyll github-pages setup as this step is fully handled by GitHub for now.

I can pick this up. Ideally we can use something like this https://github.com/peaceiris/actions-gh-pages to improve our publishing pipeline.

1. Remove the generated .md files and add them to .gitignore.
2. Run `dokkaJekyll` on post-merge.
3. Run `actions-gh-pages` just after to build the website and publish it.

**Comment by arturbosch** [comment]
> > 2. Invest time in making running the dokkaJekyll task only on documentation deploy. I think we do not need to check in the kdoc api or do I miss something? This will result in a different jekyll github-pages setup as this step is fully handled by GitHub for now.
> 
> I can pick this up. Ideally we can use something like this https://github.com/peaceiris/actions-gh-pages to improve our publishing pipeline.
> 
> 1. Remove the generated .md files and add them to .gitignore.
> 2. Run `dokkaJekyll` on post-merge.
> 3. Run `actions-gh-pages` just after to build the website and publish it.

That would be awesome @cortinico !!
dokka leads to a lot of unnecessary changes -> https://github.com/detekt/detekt/pull/3163

**Comment by cortinico** [comment]
Should we do it after we merge this?

**Review by schalkms — APPROVED** [review]
I’m fine with both approaches.

**Review by cortinico — APPROVED** [review]

**Comment by arturbosch** [comment]
@schalkms @cortinico I would like to close this PR as it only introduces unnecessary ~400 file changes

**Comment by schalkms** [comment]
@arturbosch that's okay for me.

**Pull request closed without merging**
