### PR TITLE
Remove txt report

### PR DESCRIPTION
**Pull request by BraisGabin**
I remember that someone talked about this before. The `txt` report is kind of useless. The information that if give is not easy to read by a human and the information is not that interesting for a script to parse. I can imagine people to use it to count the number of issues based on the number of lines in that file. But I think that's not a good reason to keep a `txt`. If someone wants that they can build their own reporter that just write the count.

The only use case for it is to manually create a `baseline`. But that's a really odd use case. And if you really want to do that you can create it automatically and them hand-craft it from there.

So for those reasons I vote to remove it.

### CODE REVIEW

**Comment by 3flex** [comment]
One helpful thing is that it's the easiest format to review from a CLI after a detekt run. And it's also easy to concatenate that output into a file instead.

> The txt report is kind of useless. The information that if give is not easy to read by a human and the information is not that interesting for a script to parse.

Instead of removing it, we can improve it so it's more usable for human readers, I wouldn't expect scripts to parse it, that's what #6879 is for.

**Comment by cortinico** [comment]
> Instead of removing it, we can improve it so it's more usable for human readers, I wouldn't expect scripts to parse it, that's what #6879 is for.

Isn't the MD format already serving this same need? If so we could just remove `txt` or "alias" it to output the same output as the md reported

**Comment by 3flex** [comment]
> Isn't the MD format already serving this same need?

I guess it does - TXT output is more concise though.

Personally I rely on Gradle output and never look at the reports so I'm not personally affected by this, but it's not exactly a maintenance burden to keep it and others might use it. But we can revert if anyone complains after an RC :)

**Review by cortinico — APPROVED** [review]
Yup agree on potentially removing this now

**Comment by 3flex** [comment]
LGTM after a rebase

**Pull request merged**
