### PR TITLE
Replace @since KDoc tag with @SinceDetekt

### PR DESCRIPTION
**Pull request by marschwar**
This also belongs to #3562 and replaces the rarely used `@since` KDoc tag with a `@SinceDetekt` annotation. Name and structure are "inspired by" `@kotlin.SinceKotlin`.

### CODE REVIEW

**Comment by cortinico** [comment]
Can I ask you to rebase @marschwar?
Specifically the `@since` annotation was addressed in #3569. It was a stale annotation that clashed with the `@active` annotation we already have, so I've cleaned it up.

**Comment by marschwar** [comment]
What do you mean by stale? If the `@since` tag should not be used, then I can just delete this PR. I was thinking there should be a `@SinceDetekt` and a `@ActiveByDefault` annotation. But maybe there is only the need for the latter. Let me know what you think.

**Comment by cortinico** [comment]
> What do you mean by stale?

We had a couple of occurrences and we were not really using it (e.g. in 1.16.0 we enabled several rules but never really annotated those with `@since`).

I belive we should have an `@ActiveByDefault` with a `since : String` parameter.

**Comment by marschwar** [comment]
Ok. I'll close this one.

**Pull request closed without merging**
