### PR TITLE
Upgrade to GE enterprise 3.10

### PR DESCRIPTION
**Pull request by chao2zhang**
Release notes: https://gradle.com/enterprise/releases/2022.2/

### CODE REVIEW

**Comment by 3flex** [comment]
I'm not opposed, as long as someone remembers to update it from time to time - Renovate bot doesn't check versions in the settings file. That's why using the default version from Gradle itself made sense, because the wrapper is updated regularly, and Gradle updates the GE plugin version in new Gradle releases.

**Review by 3flex — APPROVED** [review]

**Comment by chao2zhang** [comment]
I should have given more context: This is an explicit request from the Gradle team (I assume they want to use detekt to stress test their new versions).

**Comment by chao2zhang** [comment]
Linking back to the comment https://github.com/detekt/detekt/pull/4691#discussion_r846171568

**Comment by 3flex** [comment]
Where did Gradle Inc. specifically request we don't fall behind? Didn't see it mentioned in that comment you linked. If the request came through other channels then that's OK too.

If it's that important to them then maybe they'll raise PRs when new versions of the plugin are released :)

**Comment by chao2zhang** [comment]
GE 3.10 is coming with Gradle 7.5, which is not released yet. They asked to upgrade the GE plugin version ahead of Gradle. The linked comment was their acknowledgment of the fact that we preferred not to pin the version, but they still asked for pinning the GE version ahead of Gradle.

**Pull request merged**
