### PR TITLE
[WIP] :construction: Setup danger :construction:

### PR DESCRIPTION
**Pull request by BraisGabin**
:construction: :construction: :construction:

I'm using this PR to test how Danger works and set it up.

:construction: :construction: :construction:

### CODE REVIEW

**Review by cortinico — COMMENTED** [review]
Thanks for looking into this 🎉 

I have a couple of feedback:
- I was looking into using danger-kotlin https://github.com/danger/kotlin as we could detekt the dangerfile :)
  - Sadly I was stopped by this issue https://github.com/danger/kotlin/issues/228 when testing locally
- If we don't use Danger Kotlin, I would suggest we use Danger JS instead of Danger Ruby. Mostly as we already have a Node package in the repo (the website) and having a Ruby project would increase the amount of noise that the Renovate bot creates

**Comment by BraisGabin** [comment]
I just don't understand `npm`/`yarn` and all the `js` ecosystem :(

The Danger JS documentation seems to be written for people that know what those tools do and their conventions.

**Comment by cortinico** [comment]
> The Danger JS documentation seems to be written for people that know what those tools do and their conventions.

Agree. It assumes you already have a `package.json` and so. I've pushed [3ec0c3a](https://github.com/detekt/detekt/pull/5084/commits/3ec0c3ad8a8172dc60700fd40d0b43479a843eed) which creates a `bots` folder with a private module inside.

This will make easier to test danger locally with `cd bot && yarn && yarn danger ...`

**Comment by cortinico** [comment]
Can I take this over @BraisGabin ?

**Comment by BraisGabin** [comment]
Yes

**Comment by BraisGabin** [comment]
I'm closing this in favor of the Nico's work. I'm not removing the branch. Nico you can use it or remove the branch as you prefer ;).

**Comment by cortinico** [comment]
> I'm closing this in favor of the Nico's work. I'm not removing the branch. Nico you can use it or remove the branch as you prefer ;).

Yup will send it over in the next days as a separate PR

**Pull request closed without merging**
