### PR TITLE
Prepare Detekt 1.16.0-RC2

### PR DESCRIPTION
**Pull request by cortinico**
Time to bake a new RC 🎉 
This will hopefully be the last one before we release `1.16.0` stable.

### CODE REVIEW

**Review by BraisGabin — APPROVED** [review]

**Review by schalkms — APPROVED** [review]

**Comment by chao2zhang** [comment]
Should we merge this asap?

We probably also need to revert `https://github.com/detekt/detekt/commit/7cd69d21ed13f3109254100532509790db33e320` since I merged that PR in before finding out about RC2 release.

**Comment by cortinico** [comment]
> Should we merge this asap?

This has broken tests. I still haven't managed to investigate why.

> We probably also need to revert `https://github.com/detekt/detekt/commit/7cd69d21ed13f3109254100532509790db33e320` since I merged that PR in before finding out about RC2 release.

I don't think it's a major problem. We could still bake a RC3 after this.

**Comment by chao2zhang** [comment]
Another problem I found is that the `default-detekt-config.yml` inside  `https://search.maven.org/artifact/io.gitlab.arturbosch.detekt/detekt-core/1.16.0-RC2/jar`is still referring to the rules in RC1.

**Comment by chao2zhang** [comment]
@cortinico I have a fix. We need to fix the int tests after #3450. I will also look into why gradle testkit tests are not picking up the latest code (i assume it is `mavenLocal()` that may have an impact)
```
diff --git a/detekt-gradle-plugin/src/intTest/kotlin/io/gitlab/arturbosch/detekt/CreateBaselineTaskDslTest.kt b/detekt-gradle-plugin/src/intTest/kotlin/io/gitlab/arturbosch/detekt/CreateBaselineTaskDslTest.kt
index 8fd648d30..39ada1f06 100644
--- a/detekt-gradle-plugin/src/intTest/kotlin/io/gitlab/arturbosch/detekt/CreateBaselineTaskDslTest.kt
+++ b/detekt-gradle-plugin/src/intTest/kotlin/io/gitlab/arturbosch/detekt/CreateBaselineTaskDslTest.kt
@@ -1,6 +1,7 @@
 package io.gitlab.arturbosch.detekt
 
 import io.gitlab.arturbosch.detekt.testkit.DslTestBuilder
+import io.gitlab.arturbosch.detekt.testkit.ProjectLayout
 import org.assertj.core.api.Assertions.assertThat
 import org.gradle.testkit.runner.TaskOutcome
 import org.spekframework.spek2.Spek
@@ -14,9 +15,17 @@ internal class CreateBaselineTaskDslTest : Spek({
                     val detektConfig = """
                         |detekt {
                         |   baseline = file("build/baseline.xml")
+                        |   buildUponDefaultConfig = true
                         |}
                         """
+
+                    val projectLayout = ProjectLayout(
+                        numberOfSourceFilesInRootPerSourceDir = 15,
+                        numberOfCodeSmellsInRootPerSourceDir = 15
+                    )
+
                     val gradleRunner = builder
+                        .withProjectLayout(projectLayout)
                         .withDetektConfig(detektConfig)
                         .build()
 
diff --git a/detekt-gradle-plugin/src/intTest/kotlin/io/gitlab/arturbosch/detekt/testkit/DslGradleRunner.kt b/detekt-gradle-plugin/src/intTest/kotlin/io/gitlab/arturbosch/detekt/testkit/DslGradleRunner.kt
index 63bb874ba..9313d8648 100644
--- a/detekt-gradle-plugin/src/intTest/kotlin/io/gitlab/arturbosch/detekt/testkit/DslGradleRunner.kt
+++ b/detekt-gradle-plugin/src/intTest/kotlin/io/gitlab/arturbosch/detekt/testkit/DslGradleRunner.kt
@@ -17,7 +17,9 @@ class DslGradleRunner @Suppress("LongParameterList") constructor(
     val dryRun: Boolean = false
 ) {
 
-    private val rootDir: File = Files.createTempDirectory("applyPlugin").toFile().apply { deleteOnExit() }
+    private val rootDir: File = Files.createTempDirectory("applyPlugin")
+        .toFile()
+        .apply { deleteOnExit() } // Comment out when debugging Gradle testkit tests.
     private val randomString = UUID.randomUUID().toString()
 
     private val settingsContent = """
```

**Comment by cortinico** [comment]
> Another problem I found is that the `default-detekt-config.yml` inside `https://search.maven.org/artifact/io.gitlab.arturbosch.detekt/detekt-core/1.16.0-RC2/jar`is still referring to the rules in RC1.

Let's tackle this as a separate problem. I also believe this requires an RC3 before we can fully release a `1.16.0`.

> @cortinico I have a fix. 

Thanks for that. I've actually applied a different fix that relies on creating a Baseline file. Given that we have a testing API for that, let's use it :)

> We need to fix the int tests after #3450. I will also look into why gradle testkit tests are not picking up the latest code (i assume it is `mavenLocal()` that may have an impact)

Yeah that's annoying. Specifically as we notice those failures only once we publish a new version

**Pull request merged**
