### PR TITLE
Use `detekt-versions.properties` instead of `versions.properties`

### PR DESCRIPTION
**Pull request by atulgpt**
Maybe fixes https://github.com/detekt/detekt/issues/5968

I am new to Gradle plugins and Gradle-related code. So this may be some issues or partial implementation

### CODE REVIEW

**Comment by atulgpt** [comment]
Oops, all checks failed. It is harder than I thought 😅

**Comment by cortinico** [comment]
nit: `detekt-versions.properties` is probably better

**Comment by atulgpt** [comment]
> nit: `detekt-versions.properties` is probably better

I thought in the folder `detekt` we would keep all types of `*.properties` or other autogenerated files. That's why I went for folder.

BTW do you know how to fix the CI?

**Comment by cortinico** [comment]
> BTW do you know how to fix the CI?

Not sure but I'd give the file rename a try

**Comment by atulgpt** [comment]
> Not sure but I'd give the file rename a try

File rename to `detekt-versions.properties`?

**Comment by atulgpt** [comment]
> > BTW do you know how to fix the CI?
> 
> Not sure but I'd give the file rename a try

Yup it worked

**Review by cortinico — APPROVED** [review]

**Pull request merged**
