### PR TITLE
No experimental type solving

### PR DESCRIPTION
**Pull request by BraisGabin**
From: with https://github.com/detekt/detekt/discussions/4959

Right now a lot of our rules use type-solving and it is battle tested. It works! But we still say in the documentation that it is "experimental" but, to me, it is not experimental at all. It's one of the core features of detekt.

So I would like to remove the "experimental tag" from the type-solving, what do you think?

### CODE REVIEW

**Comment by 3flex** [comment]
In general I support this, but I'd seen https://github.com/detekt/detekt/issues/4465 as requiring a solution before calling this stable (at least when running detekt from Gradle).

Functional test coverage is also lacking.

**Comment by BraisGabin** [comment]
What does it mean experimental in this context? Those tasks don't have pulished edges but they are stable, right? I mean, could we track anything new as an improvement?

**Comment by 3flex** [comment]
I've listed a number of related issues in #4465 which still don't have a proper fix, though there are some workarounds in place now to quiet the console output or offer config workarounds.

Those are the kinds of open issues that make me suggest that this feature is still somewhat experimental.

The feature works in most common cases though, and we're generally aware of the outstanding issues. That's why I'm not totally opposed to merging this, since we're not enabling it by default or calling it stable just yet.

**Comment by BraisGabin** [comment]
> The feature works in most common cases though, and we're generally aware of the outstanding issues. That's why I'm not totally opposed to merging this, since we're not enabling it by default or calling it stable just yet.

@3flex I understand your concerns, I know that we need to pulish some edges but in general it is stable and we should promote it. It finds lots of issues and there is no good reason to don't use it.

**Comment by BraisGabin** [comment]
Closing this as there is not consensous on it. We could continue the discussion on an issue and recreate another PR once we decide.

**Pull request closed without merging**
