### PR TITLE
Prepare Release 1.23.6

### PR DESCRIPTION
**Pull request by cortinico**
Time for a new point release

### CODE REVIEW

**Comment by cortinico** [comment]
CI will fail here as I haven't published the artifacts yet

**Comment by cortinico** [comment]
I'm waiting for:
- https://github.com/detekt/detekt/pull/7084

To be merged before publishing the artifacts as we probably want it inside .6 as well

**Comment by BraisGabin** [comment]
Merged!!

**Comment by cortinico** [comment]
@detekt/maintainers this is ready to be approved and merged 👍

**Review by 3flex — APPROVED** [review]

**Pull request merged**
