### PR TITLE
Merge logic of baseline result mapping into one class.

### LINKED ISSUE #6882: Refactor how we handle `Baseline`
The code that handles the baseline feature is a bit messy. We have 3 different files that could be simplified in only one:

- `BaselineResultMapping`
- `BaselineFilteredResult`
- `BaselineFacade`

In all that code we are using the concept of `Detektion` that we don't need at all. My idea would be to merge all the logic in one single file `BaselineResultMapping` and rewrite the tests to check the cases. They aren't that much so we can take that as a single unit.

### PR DESCRIPTION
**Pull request by MaximSysoev**
Merge `BaselineResultMapping` `BaselineFilteredResult` and `BaselineFacade` into `BaselineResultMapping` and also merge corresponding test specs as described here #6882.

Close #6882

### CODE REVIEW

**Review by cortinico — APPROVED** [review]
Nice cleanup :)

**Comment by MaximSysoev** [comment]
> Nice cleanup :)

Cool, thanks!

Could you merge it? I don't have write access.

**Comment by cortinico** [comment]
> Could you merge it? I don't have write access.

Generally we wait around ~24h to allow other maintainers to also chime in (specifically @BraisGabin as he originally requested this change).
We can merge it later today 👍

**Comment by MaximSysoev** [comment]
> > Could you merge it? I don't have write access.
> 
> Generally we wait around ~24h to allow other maintainers to also chime in (specifically @BraisGabin as he originally requested this change). We can merge it later today 👍

Ok, I see :) Thank you :) 👍

**Review by BraisGabin — APPROVED** [review]
Looks good! Thank you :)

**Pull request merged**
