### PR TITLE
 Fix documentation for deprecated 'reports' object (Issue #5908)

### PR DESCRIPTION
**Pull request by BeBAKE**

### CODE REVIEW

**Comment by BeBAKE** [comment]
Hi,@cortinico 
I wanted to let you know that I've submitted a draft pull request for my recent changes to the documentation. However, one of the checks has failed. Specifically, the codecov report shows that merging my changes into the main branch would decrease coverage by 0.11%. The diff coverage is 88.88%.
I'm not sure why this is happening, and I would appreciate your guidance in resolving this issue.  Can you please take a look at the failed check and let me know what I can do to fix the coverage issue?
Thank you for your time and help.

**Review by cortinico — COMMENTED** [review]
Thanks for sending this,

Can you also amend all the other unrelated changes like whitespaces and so you have in your diff?

**Comment by BeBAKE** [comment]
@cortinico I am really sorry but i am new to open source so i had no idea how to improve this existing PR.
I have made another PR that will be ready as the checks gets completed. 
I am extremely sorry for this kind of behaviour, I apologize for any inconvenience caused.

**Comment by 3flex** [comment]
> how to improve this existing PR

There are a few ways, but the easiest way is to make your changes, commit them, then push the new commits to your remote repository again.

For more info, try:
https://www.atlassian.com/git/tutorials/saving-changes
https://www.atlassian.com/git/tutorials/syncing/git-push

There are lots of sources of intro level information out there!

**Pull request closed without merging**
