### PR TITLE
Upgrade to Gradle 7

### PR DESCRIPTION
**Pull request by chao2zhang**
This is to prepare for #3688

### CODE REVIEW

**Comment by 3flex** [comment]
Are you working on the build failures?

I don't mind doing it but I don't want to duplicate effort.

**Comment by chao2zhang** [comment]
Thanks for offering the help. I am attempting to fix this in https://github.com/detekt/detekt/pull/3691

**Comment by 3flex** [comment]
Tests are flaky... is that a known issue with the detekt build? I had to rerun the checks twice before everything came up green.

**Comment by chao2zhang** [comment]
> is that a known issue with the detekt build?

I have been noticing that lately as well. Since we are seeing out-of-memory issues, the first thing I would like to try is to bump Gradle JVM heap sizes.

**Review by BraisGabin — APPROVED** [review]

**Pull request merged**
