### PR TITLE
Fix false positive in case of invoke operator

### PR DESCRIPTION
**Pull request by atulgpt**
Fixes https://github.com/detekt/detekt/issues/4435

### CODE REVIEW

**Comment by atulgpt** [comment]
Hi, @BraisGabin / @TWiStErRob / @cortinico can you guys review this PR :) Let me know if any changes are required

**Review by BraisGabin — APPROVED** [review]
LGTM Thanks!

**Comment by BraisGabin** [comment]
Sorry for the delay. Could you fix the conflicts? I think they are going to be big because this rule was splitted in 3. But the test and code looks good :)

**Comment by atulgpt** [comment]
Hi @BraisGabin one test `RedundantVisibilityModifierRuleSpec > Explicit API mode > does not report public function in class if explicit API mode is set to strict()` is failing while in the local same test is getting passes. Any idea how to make CI happy?

**Comment by BraisGabin** [comment]
No idea, I'm re-running the task to see if it still happens.

**Comment by atulgpt** [comment]
@BraisGabin seemed like intermittent issue. Pasting the stack trace for the record
```
RedundantVisibilityModifierRuleSpec > Explicit API mode > does not report public function in class if explicit API mode is set to strict() FAILED
    io.mockk.MockKException: Can't instantiate proxy for class org.jetbrains.kotlin.config.LanguageVersionSettings
        at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:64)
        at io.mockk.impl.instantiation.AbstractMockFactory.newProxy$default(AbstractMockFactory.kt:24)
        at io.mockk.impl.instantiation.AbstractMockFactory.mockk(AbstractMockFactory.kt:59)
        at io.gitlab.arturbosch.detekt.rules.style.RedundantVisibilityModifierRuleSpec$Explicit API mode.mockCompilerResources(RedundantVisibilityModifierRuleSpec.kt:236)
        at io.gitlab.arturbosch.detekt.rules.style.RedundantVisibilityModifierRuleSpec$Explicit API mode.does not report public function in class if explicit API mode is set to strict(RedundantVisibilityModifierRuleSpec.kt:205)

        Caused by:
        io.mockk.proxy.MockKAgentException: Value for this result is not assigned
            at io.mockk.proxy.common.CancelableResult.get(CancelableResult.kt:18)
            at io.mockk.impl.instantiation.JvmMockFactory.newProxy(JvmMockFactory.kt:44)
            ... 4 more
```
logs at [here](https://github.com/detekt/detekt/actions/runs/4236224656/jobs/7360784676)

**Comment by BraisGabin** [comment]
It seems like an issue at `mockk`. I saw some issues related with that exception message at their repo. Anyway, merging!

**Pull request merged**
