### PR TITLE
Review Ktlint links

### PR DESCRIPTION
**Pull request by TWiStErRob**
Following #6103 I was randomly clicking 5 links on the [website](https://detekt.dev/docs/next/rules/formatting), and found the only one that wasn't replaced 🍀.

Also reviewed links to be locked in time with easy to reference to reference.

### CODE REVIEW

**Comment by marschwar** [comment]
Thank you for doing this. I thought I had already gone through the versioned docs, but obviously I had not. All those rules should also have their links fixed. At least for 1.23.0 (ktlint 0.49.1) and maybe also for 1.22.0 (ktlint 0.47.1).

**Comment by TWiStErRob** [comment]
I hadn't replace historical links, just commit hashes referring to ktlint.
1.23.0 still has broken links everywhere.

**Review by cortinico — APPROVED** [review]

**Comment by marschwar** [comment]
> I hadn't replace historical links, just commit hashes referring to ktlint.
> 1.23.0 still has broken links everywhere.

Should we/I create  a separate PR for the links in 1.23 and 1.22? That one should probably also picked for the 1.x branch.

**Review by schalkms — APPROVED** [review]

**Review by marschwar — APPROVED** [review]

**Comment by marschwar** [comment]
I created #6298 to fix the versioned docs for 1.23.0. The version 1.22.0 was already fixed.

**Pull request merged**
