### PR TITLE
Avoid overlapping outputs

### PR DESCRIPTION
**Pull request by 3flex**
javadocJar & publishPluginJar output to the same file path, as did
sourcesJar & publishPluginJavaDocsJar, preventing Gradle's up-to-date
checks from working properly.

### CODE REVIEW

**Review by schalkms — APPROVED** [review]

**Review by BraisGabin — APPROVED** [review]

**Comment by cortinico** [comment]
When releasing `1.18.0-RC1` I noticed that this PR is blocking the release process.
Specifically the sources.jar and the javadoc.jar are missing for `detekt-gradle-plugin`.

Maven Central is not allowing the whole bundle to be published if those artifacts are missing.

Should we revert this change?

**Comment by schalkms** [comment]
> Should we revert this change?

I don't see an alternative.

**Comment by 3flex** [comment]
> I don't see an alternative.

I'd argue there's no reason to publish the plugin artifact to Maven Central anyway, since it's already published to the Gradle Plugin Portal.

That's probably why the two publishing methods provided by Gradle don't work well together in this case (overlapping outputs) since it's not a typical setup.

**Comment by cortinico** [comment]
> I'd argue there's no reason to publish the plugin artifact to Maven Central anyway, since it's already published to the Gradle Plugin Portal.

I'm unsure about the historical reason why `detekt-gradle-plugin` is on Central as well.

One thing to point out is that `detekt-gradle-plugin` relies on `detekt-bom` and a lot of other deps that are published on Central. So it sounds reasonable to me that we publish all of our artifacts to me on Central + we offer `detekt-gradle-plugin` as a convenience for Gradle users.

**Pull request merged**
