### PR TITLE
Add Docs for 1.23.2

### PR DESCRIPTION
**Pull request by cortinico**
As our website generates from `main`, I'm updating all the docs with the point release docs from the `release/1.x` branch.

### CODE REVIEW

**Comment by 3flex** [comment]
Tricky to review without reading the whole thing 😕

Can fix later if anything is amiss.

**Review by 3flex — APPROVED** [review]

**Comment by 3flex** [comment]
Thanks - I often review on my phone (!) so didn't have diff tools handy but will keep that in mind next time :)

**Comment by TWiStErRob** [comment]
Yeah, same :) GH UI is pretty good for many things.

**Comment by TWiStErRob** [comment]
I did a diff and found 2 interesting issues:
 * #6602
 * #6603

**Pull request merged**
