### PR TITLE
Gradle to 6.8

### PR DESCRIPTION
**Pull request by cortinico**
Gradle 6.8 just got released: https://github.com/gradle/gradle/releases/tag/v6.8.0

### CODE REVIEW

**Comment by chao2zhang** [comment]
I believe this is covered by https://github.com/detekt/detekt/pull/3254

**Comment by cortinico** [comment]
> I believe this is covered by #3254

Oops you're right my bad

**Comment by BraisGabin** [comment]
I think that we could merge this regardless. It's related but this PR doesn't depend in the other one.

**Comment by cortinico** [comment]
Reopening then

**Review by BraisGabin — APPROVED** [review]

**Review by schalkms — APPROVED** [review]

**Pull request merged**
