### PR TITLE
Fix `CastToNullableType` warning on same or parent type

### PR DESCRIPTION
**Pull request by atulgpt**
Fixes: https://github.com/detekt/detekt/issues/6676

### CODE REVIEW

**Comment by cortinico** [comment]
Do we want this on the 1.x? It's quite of an invasive change as the rule will stop working for users that are nto using TR

**Comment by cortinico** [comment]
> @cortinico I do not have any hard preferences here but speaking from the past data we have made these types of changes even in detekt releases like 1.x to 1.(x+1)

Yup but this will end up in 1.23.x+1

**Review by BraisGabin — APPROVED** [review]

**Comment by atulgpt** [comment]
> > @cortinico I do not have any hard preferences here but speaking from the past data we have made these types of changes even in detekt releases like 1.x to 1.(x+1)
> 
> Yup but this will end up in 1.23.x+1

Got your point 😅 . Since it's patch version I think we should not

**Comment by TWiStErRob** [comment]
Why are we limiting to 1.23.x+1? Is there anything wrong with releasing 1.24?

**Comment by cortinico** [comment]
> Why are we limiting to 1.23.x+1? Is there anything wrong with releasing 1.24?

Yes. If so we would have to ship all the new rules in `1.24` and I don't think we have the capacity to do so. Therefore we committed to ship only bugfixes for 1.23.x and version bumps (as those are ecosystem blockers)

**Comment by TWiStErRob** [comment]
Ah, I see, thanks. Although the "have to ship all the new rules" seems like a self-imposed requirement. Anyway, makes sense to focus on backporting important fixes only!

**Pull request merged**
