### PR TITLE
Move Suppressor from `core` module  to `api` module

### PR DESCRIPTION
**Pull request by gouri-panda**
closes: #4932 

* Moved `Suppressor` from `core` to `api`
* Renamed `core/Suppressor.kt` to `InnerSuppressor`
* Updated `detekt-api.api` file

### CODE REVIEW

**Comment by BraisGabin** [comment]
This doesn't close #4932 right now. How do the core load the clases that third-party plugins provide? I recommend you to see how `FileProcessListener` or `ReportingExtension` work.

**Comment by BraisGabin** [comment]
@gouri-panda are you going to continue with this one?

**Comment by gouri-panda** [comment]
@BraisGabin Sure! Let me try once more :)

**Comment by BraisGabin** [comment]
I'm closing this one as stale. If you have time to work again on it just create a new PR ;)

**Pull request closed without merging**
