### PR TITLE
Allow additionalJavaSourceRootPaths to be defined on @KotlinCoreEnvironmentTest

### PR DESCRIPTION
**Pull request by marschwar**
This relates to #4575 and exposes the `additionalJavaSourceRootPaths`property from `KotlinCoreEnvironmentWrapper.createEnvironment` as `additionalJavaSourcePaths` in the KotlinCoreEnvironmentTest annotation.

There are only very few instances where this feature is needed, so the list of additionalJavaSourcePaths defaults to an empty list.

Changes in the tests are mostly indentation because I introduced two top level nested classes to split into WithDefaultSources and WithAdditionalJavaSources.

### CODE REVIEW

**Review by BraisGabin — APPROVED** [review]
This PR shows the need of #4705 (and nearly all our tests). We have a lot of multiline strings and I don't even know how should we indent them "properly".

**Comment by marschwar** [comment]
I don't think I understand that comment. I introduced and additional level of nesting and that changes the indentation. I do not see this as evidence that we need the multi-line string rule - even though it might still be a good rule to have.

**Comment by BraisGabin** [comment]
> I don't think I understand that comment. I introduced and additional level of nesting and that changes the indentation. I do not see this as evidence that we need the multi-line string rule - even though it might still be a good rule to have.

Captura de pantalla 2022-04-30 a las 13 02 48

You are adding indentation to your code, but if you see that code inside the multiline didn't change its indentation. The code inside the multiline string has less indentation that the opening multiline operator `"""`.

**Comment by marschwar** [comment]
Ok, I get it now. Is there a correct way to indent multi line strings?

**Comment by BraisGabin** [comment]
I assume that there should be. But I don't know which it is. To me, the important part is to be consistent.

**Comment by schalkms** [comment]
@marschwar @BraisGabin any plans to get this ahead?

**Comment by marschwar** [comment]
From my point of view this is ready.

**Comment by BraisGabin** [comment]
More than 1 month with an approve and no open comments seems fair to merge to me so...

**Pull request merged**
