### PR TITLE
Made all reports have uniform ids

### PR DESCRIPTION
**Pull request by lexa-diky**

### CODE REVIEW

**Comment by BraisGabin** [comment]
Shouldn't we align in the other way? Just change the sarif Id? To be honest I don't understand why they got unaligned in the first place.

**Comment by lexa-diky** [comment]
That's also an option, this will be less breaking, but I suggest sill fixing report names in `id` property.

+ now thinking of shorter names in this MR, maybe a bit more cryptic `XmlOutputReport` is better in this case, at least it's not implying that this is some standard `THE XML` report, but just some detekt specific thing.

@BraisGabin could you please summon any third person to this PR, to have final vote?

**Comment by BraisGabin** [comment]
About "the xml" we could even rename it to "checkstyle", because that's the format.

**Comment by cortinico** [comment]
Closing because of #6505

**Pull request closed without merging**
