### PR TITLE
New rule: DontDowncastCollectionTypes

### PR DESCRIPTION
**Pull request by cortinico**
I'm proposing a new rule: `DontDowncastCollectionTypes`

Down-casting immutable types from kotlin.collections should be discouraged.
The result of the downcast is platform specific and can lead to unexpected crashes.
Prefer to use instead the `toMutable<Type>()` functions.

### Non-compliant
```kotlin
val list : List<Int> = getAList()
if (list is MutableList) {
    list.add(42)
}

(list as MutableList).add(42)
```

### Compliant 
```kotlin
val list : List<Int> = getAList()
list.toMutableList().add(42)
```

Happy to discuss if we want to adapt it to check casts against Java concrete collection types (e.g. `ArrayList`, etc.).

### CODE REVIEW

**Comment by cortinico** [comment]
This rule is inspired from Effective Kotlin: Item 1 - Limit Mutability (credits to @MarcinMoskala)

**Comment by BraisGabin** [comment]
Great rule! I think that it would be good to think of ArrayList at least because it exists in kotlin (with a type alias).

And I'm not sure about the name. But I can't think of anyone better.

**Review by schalkms — APPROVED** [review]
Great rule!

**Comment by cortinico** [comment]
> Great rule! I think that it would be good to think of ArrayList at least because it exists in kotlin (with a type alias).

I've added those 5 type aliases to the mutable types to consider: https://github.com/JetBrains/kotlin/blob/46b7a774b558001c136be225cf4367fa09ba1aee/libraries/stdlib/jvm/src/kotlin/collections/TypeAliases.kt#L13-L17

**Review by BraisGabin — APPROVED** [review]

**Pull request merged**
