### PR TITLE
#5014 Fix MaxChainedCallsOnSameLine false positives

### PR DESCRIPTION
**Pull request by dzirbel**

### CODE REVIEW

**Comment by dzirbel** [comment]
I've now run on the detekt codebase (with a max of 7 since there are [some](https://github.com/detekt/detekt/blob/main/detekt-cli/src/test/kotlin/io/gitlab/arturbosch/detekt/cli/CliArgsSpec.kt#L18) violations longer than 5) to verify that there aren't any more obvious false positives.

There are still interesting cases ([example](https://github.com/detekt/detekt/blob/main/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingRule.kt#L92)) with fully-qualified class names which still violate this rule; thoughts on what to do there? I haven't looked into it yet, but I'm not certain whether it will be possible to differentiate those from normal qualified expressions.

**Review by BraisGabin — APPROVED** [review]

**Comment by BraisGabin** [comment]
I think that we will need to use type solving.

**Review by amitdash291 — APPROVED** [review]

**Comment by amitdash291** [comment]
> There are still interesting cases ([example](https://github.com/detekt/detekt/blob/main/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingRule.kt#L92)) with fully-qualified class names which still violate this rule; thoughts on what to do there? I haven't looked into it yet, but I'm not certain whether it will be possible to differentiate those from normal qualified expressions.

Not sure if this example qualifies for `MaxChainedCallsOnSameLine` violation, but it is something that needs cleaning up anyway.

**Comment by schalkms** [comment]
> I think that we will need to use type solving.

How would that rule benefit from type solving? Could you please highlight an example?

**Review by schalkms — APPROVED** [review]

**Comment by dzirbel** [comment]
> > I think that we will need to use type solving.
> 
> How would that rule benefit from type solving? Could you please highlight an example?

This was in response to this [example](https://github.com/detekt/detekt/blob/main/detekt-formatting/src/main/kotlin/io/gitlab/arturbosch/detekt/formatting/FormattingRule.kt#L92) of a fully-qualified class name which this rule currently flags. Probably this rule should ignore such cases (although this one can just be imported), but I agree that type resolution is probably necessary to determine whether a chained calls are from a fully qualified class name. I'll open a separate issue to track/discuss that.

**Review by BraisGabin — APPROVED** [review]

**Pull request merged**
