### PR TITLE
Prepare Detekt 1.18.1

### PR DESCRIPTION
**Pull request by cortinico**
This is the branch for a point release of Detekt `1.18.1`.

I've picked the following PRs:

- Allow active, excludes and includes in the rule-set configuration - [#4045](https://github.com/detekt/detekt/pull/4045)
- Remove Error from ThrowingExceptionsWithoutMessageOrCause because is a common name - [#4046](https://github.com/detekt/detekt/pull/4046)
- Fix issue IDs for ReferentialEquality and DoubleMutability - [#4040](https://github.com/detekt/detekt/pull/4040)

Please let me know if you think there is more to be picked up 👍

### CODE REVIEW

**Comment by chao2zhang** [comment]
I assume the check failures are be because we have not published Detekt artifacts yet. Is it correct?

**Review by BraisGabin — APPROVED** [review]

**Comment by cortinico** [comment]
> I assume the check failures are be because we have not published Detekt artifacts yet. Is it correct?

Yes that's correct 👍

**Comment by cortinico** [comment]
I would like to include this as well https://github.com/detekt/detekt/pull/4071

**Comment by cortinico** [comment]
I've just published `1.18.1` to Central. Waiting for CI results to be green and then we can merge this 👍

**Comment by cortinico** [comment]
> then we can merge this 👍

Side note: this has to be done manually and not via Github UI as there are conflicts and I don't want to mess up similarly to how we did with `1.17.1`.

**Comment by geojakes** [comment]
@BraisGabin My apologies. When I used snapshots, I was running into some other issues so was truly blocked on this for a couple weeks.

**Comment by cortinico** [comment]
> When I used snapshots, I was running into some other issues so was truly blocked on this for a couple weeks.

Which other issues?

**Comment by geojakes** [comment]
Specifically, we use a jar in our scripts as well as a version pulled in by gradle during build. Moving to a snapshot of main but using a static jar would create disparity in what devs scan locally versus what detekt would flag in the CI.

**Comment by cortinico** [comment]
> would create disparity in what devs scan locally versus what detekt would flag in the CI

Can't you use the Detekt SNAPSHOT jar for both scenarios?

**Comment by geojakes** [comment]
@cortinico There is a SNAPSHOT jar?

**Comment by cortinico** [comment]
> @cortinico There is a SNAPSHOT jar?

Yes. The process of usign them is here: https://detekt.github.io/detekt/snapshots.html
They're hosted on Sonatype here: https://oss.sonatype.org/content/repositories/snapshots/io/gitlab/arturbosch/detekt/detekt-core/main-SNAPSHOT/ (those are `detekt-core` artifacts, but we publish all of them).

**Comment by geojakes** [comment]
@cortinico I totally understand how to use snapshots as mentioned in https://detekt.github.io/detekt/snapshots.html from which I got here https://oss.sonatype.org/#view-repositories;snapshots~browsestorage~io/gitlab/arturbosch/detekt which was harder to navigate. This link https://oss.sonatype.org/content/repositories/snapshots/io/gitlab/arturbosch/detekt/detekt-core/main-SNAPSHOT/ is super new to me! Thank you for pointing that out. Its going to be super useful moving forward and I'll make sure to have a note in my org about the same.

**Pull request merged**
