### PR TITLE
Don't use deprecated code

### PR DESCRIPTION
**Pull request by BraisGabin**
`application.mainClassName` is deprecated.

### CODE REVIEW

**Comment by BraisGabin** [comment]
https://github.com/johnrengelman/shadow/issues/625 we need to wait for this issue to be fixed.

**Review by schalkms — COMMENTED** [review]
That's okay. Thanks for investigation! I'll put a **blocked** tag on this PR as long as it's blocked. Please feel free to remove this tag once the issue is fixed.

**Comment by chao2zhang** [comment]
This issue is fixed, we are going to be waiting for the shadow 6.2 release.

**Review by cortinico — APPROVED** [review]

**Review by cortinico — APPROVED** [review]

**Comment by BraisGabin** [comment]
Closing in favor of #3698

**Pull request closed without merging**
