### PR TITLE
Add rule to warn on ignored return value

### PR DESCRIPTION
**Pull request by bbaldino**
Addresses #2239.

I'd consider this as draft at this point.  It works for the test cases I've provided, but I'm not familiar with all of the psi element types and I worry a bit that there may be some I missed (or perhaps a better way to detect what I am detecting).

### CODE REVIEW

**Comment by bbaldino** [comment]
Travis tests look like they're failing because I didn't update `default-detekt-yml`. Not sure how that should be updated yet, though, so will leave it as-is until I hear how to proceed there.

**Comment by BraisGabin** [comment]
> Travis tests look like they're failing because I didn't update `default-detekt-yml`. Not sure how that should be updated yet, though, so will leave it as-is until I hear how to proceed there.

Run `./gradlew generateDocumentation` and those files would be updated.

**Comment by bbaldino** [comment]
> > Travis tests look like they're failing because I didn't update `default-detekt-yml`. Not sure how that should be updated yet, though, so will leave it as-is until I hear how to proceed there.
> 
> Run `./gradlew generateDocumentation` and those files would be updated.

I ran this, but it didn't seem to result in any changes I could commit.

**Comment by bbaldino** [comment]
> > > Travis tests look like they're failing because I didn't update `default-detekt-yml`. Not sure how that should be updated yet, though, so will leave it as-is until I hear how to proceed there.
> > 
> > 
> > Run `./gradlew generateDocumentation` and those files would be updated.
> 
> I ran this, but it didn't seem to result in any changes I could commit.

Found it.  Had to add it to `PotentialBugProvider`.

**Comment by bbaldino** [comment]
I've made some more tweaks, but when testing against my code base I'm running into a lot of incorrect classifications.  I'm checking the PsiElement type of each one I find and adding handling for it, but it feels a bit like whack-a-mole and can be hard to differentiate in places where elements are nested multiple levels below where an assignment or something is actually done.  I have a feeling my lack of knowledge of the Psi types may be making this more difficult than it needs to be?  Are there some useful helpers to differentiate expressions from assignment expressions, etc.?

**Comment by schalkms** [comment]
Continuing here, because it’s easier than on Slack.
The way to go would be to take a code snippet that gets flagged by your rule and debug the Psi tree with the watch functionality in IntelliJ. I don’t think there’s some pre defined helper function in the Framework for you, which does the trick.
Please correct me if I’m wrong @3flex.

**Comment by bbaldino** [comment]
> Continuing here, because it’s easier than on Slack.
> The way to go would be to take a code snippet that gets flagged by your rule and debug the Psi tree with the watch functionality in IntelliJ. I don’t think there’s some pre defined helper function in the Framework, which does the trick for you.
> Please correct me if I’m wrong @3flex.

Ok, this is what I've been doing. Thanks for confirming.

**Comment by 3flex** [comment]
Also have a look at PsiViewer plugin for IntelliJ which I've found useful.

**Comment by bbaldino** [comment]
> Also have a look at PsiViewer plugin for IntelliJ which I've found useful.

Ah! This is super helpful.  Thanks!

**Comment by schalkms** [comment]
@bbaldino do you have an update on this PR? Do you need assistance from our side?

**Comment by bbaldino** [comment]
> @bbaldino do you have an update on this PR? Do you need assistance from our side?

Sorry for the lack of updates, work has been busy and I haven't had much time to work on this.  Where I was hung up, though, was discovering *all* the different expressions which this should apply to; finding them all and good ways to properly detect them was proving tough.

I wondered about `detekt`'s policy on rules: might it be interesting to have an initial version of this which was naive and only detected some cases?  Or are rules only merged when they are 'complete'?

**Comment by schalkms** [comment]
> I wondered about detekt's policy on rules: might it be interesting to have an initial version of this which was naive and only detected some cases? Or are rules only merged when they are 'complete'?

We haven’t had this case so far. I obviously don’t want to include rules that are buggy into detekt. In your case the rule just doesn’t flag all corner cases, which is okay. I hope that I understood you correctly.
In my opinion this rule should go into an experimental rule set.

**Comment by bbaldino** [comment]
> > I wondered about detekt's policy on rules: might it be interesting to have an initial version of this which was naive and only detected some cases? Or are rules only merged when they are 'complete'?
> 
> We haven’t had this case so far. I obviously don’t want to include rules that are buggy into detekt. In your case the rule just doesn’t flag all corner cases, which is okay. I hope that I understood you correctly.
> In my opinion this rule should go into an experimental rule set.

Yeah that makes sense and is what I was wondering.  I still have been a bit strapped for time, but I'll plan on seeing if I can focus on a smaller ruleset which can detect some cases but not give any false positives.

**Comment by schalkms** [comment]
@bbaldino great! Just pings us if you need help or assistance.

**Comment by schalkms** [comment]
Since this PR become inactive, I'm wondering if you @bbaldino still plan to work further on this PR. We are open to answer any questions you have.

**Comment by bbaldino** [comment]
Apologies for the radio silence...work got busy and I haven't had time to come back to this--and unfortunately don't think I'll be able to anytime soon.  Feel free to close this if you like, I can reopen if I ever get back around to it.

**Comment by schalkms** [comment]
@bbaldino no worries.. Thanks for the fast reply. I'll put a help wanted tag on this PR in case somebody wants to pick it up and thus help out here.

**Comment by cortinico** [comment]
@schalkms I can pick this up, can you assign this PR to me?

**Comment by BraisGabin** [comment]
All yours ;) and thanks for the help!

**Pull request closed without merging**
