### PR TITLE
Make common DetektBaseSourceTask.kt

### PR DESCRIPTION
**Pull request by atulgpt**
Maybe fixes https://github.com/detekt/detekt/issues/5940

### CODE REVIEW

**Comment by 3flex** [comment]
We'll need to have a think about whether this is the right structure to use, and I suggest it's going to box us in later if we want to make changes.

With this PR we'll have JVM-specific options are put alongside non-JVM-specific options in the extracted abstract class which makes it harder to them move them to a JVM-specific class later without breaking changes. I'd like to agree on which elements we might want to extract and treat differently. This will also let us support cases like #5947.

**Comment by atulgpt** [comment]
> We'll need to have a think about whether this is the right structure to use, and I suggest it's going to box us in later if we want to make changes.
> 
> With this PR we'll have JVM-specific options are put alongside non-JVM-specific options in the extracted abstract class which makes it harder to them move them to a JVM-specific class later without breaking changes. I'd like to agree on which elements we might want to extract and treat differently. This will also let us support cases like #5947.

Hi, @3flex I can also make a few more interfaces(based on frameworks or language they control) and then compose those interfaced in `DetektSourceTask` and make `DetektSourceTask` as `internal` so that it can't be used as public API.

But I agree we should discuss this and close this to avoid any future roadblocs

**Review by cortinico — APPROVED** [review]
Generally agree with the direction, but I second what @3flex mentioned. Let's align on this before we making changes to the task class hierarchy.

**Comment by atulgpt** [comment]
Hi @3flex, since we are on the path to 2.0 should we decide on the strategy to be followed here?

**Comment by 3flex** [comment]
I'm working on a new version of the plugin which will be ready for initial review in the next couple of weeks depending on how much time I have to spend on it. It will resolve that issue.

**Comment by atulgpt** [comment]
Ohh nice. Closing this PR then

**Pull request closed without merging**
