### PR TITLE
UnusedImports rule: fix false positives when type resolution is enabled

### LINKED ISSUE #3074: UnusedImports: Lots of false positives
## Expected Behavior
`java.util.HashMap` is not reported as unused, since the type is used in the function value parameter:
```kotlin
import java.util.HashMap

fun doesNothing(thing: HashMap<String, String>) {
    // nothing
}
```

## Observed Behavior
`java.util.HashMap` is reported as unused by UnusedImports rule.

## Steps to Reproduce
Run detekt with type resolution enabled on the code provided above.

## Context
Lots of false positives in detekt 1.13.x.

## Your Environment
* Version of detekt used: 1.13.1
* Version of Gradle used (if applicable): 6.6.1
* Operating System and version: Windows 10
* Link to your project (if it's a public repository): N/A

### PR DESCRIPTION
**Pull request by t-kameyama**
Closes #3074

### CODE REVIEW

**Comment by 3flex** [comment]
Thanks @t-kameyama, that's a big improvement! Unfortunately I still have some false positives with type resolution enabled.

Here `com.squareup.sqldelight.android.AndroidSqliteDriver` is shown as unused, but it's not.
```kotlin
import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.sqlite.db.SupportSQLiteOpenHelper
import com.squareup.sqldelight.android.AndroidSqliteDriver

internal class DbOpenHelper : SupportSQLiteOpenHelper.Callback(DATABASE_VERSION) {

    override fun onCreate(db: SupportSQLiteDatabase) {
        val driver = AndroidSqliteDriver(db)
        Database.Schema.create(driver)
    }
}
```

I also have annotations in another file which are used, but they're still being reported.

**Review by schalkms — APPROVED** [review]

**Comment by t-kameyama** [comment]
@3flex 
Fixed in 8ace339

**Comment by 3flex** [comment]
Awesome :) A couple more, where the reference resolves to a companion object...

Lots of code omitted here, but the import is reported when it's used like this:
```kotlin
import com.bluelinelabs.conductor.RouterTransaction

RouterTransaction.with(DomainListController())
```

That resolves to:
```kotlin
class RouterTransaction {
  companion object {

    @JvmStatic
    fun with(controller: Controller): RouterTransaction = RouterTransaction(controller)
  }
}
```

And another example, again, lots of code omitted:
```kotlin
import okhttp3.ConnectionSpec

ConnectionSpec.MODERN_TLS
ConnectionSpec.COMPATIBLE_TLS
```

Both of those variables sit in a companion object.

**Comment by t-kameyama** [comment]
@3flex 
Fixed in 096c4418d5387bf1513d82ffe544b291d3d8acda

**Review by 3flex — APPROVED** [review]
Amazing! I can enable the rule with TR enabled now.

Possibly there will be other cases that pop up but this resolves my initial issue.

**Comment by cortinico** [comment]
Thanks for the fix @t-kameyama 
Would you be able to cherry pick https://github.com/detekt/detekt/pull/3077 so to make sure we're not introducing further regressions in the test suite for `UnusedImports`

**Comment by t-kameyama** [comment]
@cortinico 
Fixed in 2f35b03

**Review by cortinico — APPROVED** [review]

**Comment by arturbosch** [comment]
@cortinico we can close #3077 now, right?

**Comment by cortinico** [comment]
> @cortinico we can close #3077 now, right?

Yup 👌

**Pull request merged**
