### PR TITLE
Add one minute Debt

### PR DESCRIPTION
**Pull request by VovaStelmashchuk**
I have a suggest about add one minute Debt, because a lot of rules are a one minute fix.

### CODE REVIEW

**Comment by chao2zhang** [comment]
We might need to perform a general swipe of all rules to see if they are also 1 min debt. I often laughed at myself why autoCorrectible detekt violations would take >2hours of my time to fix.

**Comment by VovaStelmashchuk** [comment]
You right. Maybe we need to add flag to Debt, like a canBeFixByAutoCorrect ?

**Comment by chao2zhang** [comment]
Sadly none of our detekt native rules are autoCorrectible. Only those imported from ktlint are.
We have #2560 to track the progress on implementing an autoCorrectible rule, so let's not divert this PR too much.

**Comment by BraisGabin** [comment]
I think that there is not issue that can be fixed in 1 minute:

- Check the report
- Create branch
- Fix issue
- Create PR

The problem is that you can fix 60 issues in 5 minutes. Because you need nerly the same time to fix one unused import that to fix 60. I don't think that any of the standard rules should use 1 minute.

**Comment by VovaStelmashchuk** [comment]
I usually fix a detekt issues in feature branch

**Comment by BraisGabin** [comment]
Would it work for you if you could change the time in the yaml configuration?

**Comment by VovaStelmashchuk** [comment]
Good point. Do detekt has with feature, or we need to implement this?

**Comment by BraisGabin** [comment]
That feature is not implemented. But before implementing it, could you open an issue explaining your use case and why you need this feature?

This feature would add complexity to the project and I'm not sure how much value it could bring. This way other people can say it's point of view.

**Comment by chao2zhang** [comment]
> I think that there is not issue that can be fixed in 1 minute:
> 
> * Check the report
> * Create branch
> * Fix issue
> * Create PR
> 
> The problem is that you can fix 60 issues in 5 minutes. Because you need nerly the same time to fix one unused import that to fix 60. I don't think that any of the standard rules should use 1 minute.

This statement makes sense. I would still like to point out that using the sum of debt of each individual finding is confusing. When we publish a PR, we fix multiple violations altogether, where each finding would take maybe 1 minute. The overhead time of creating a review may take up to 5 minutes. A more reasonable approach is to calculate the overhead (5 minutes) + the time to fix individual finding (1 minute / each), so that the total debt time is not way off the actual time spent on fixing those issues.

**Comment by BraisGabin** [comment]
We need to take some decission here. I think that this conversation is interesting and we could rethink this feature a bit. I personally use it as a metric to see how my project is going so a more realistic value would be great.

What do you think about closing this and moving it to a conversation/issue? So we can find a formula that everyone (or most of us) agree with and then implement it. We can create another issue to track the feature to cusomize the time for issue if you consider it worth it.

**Comment by BraisGabin** [comment]
Closing this. If a custom rule write wants it's rules to have 1 minute debt there's nothing in our API stopping them.

If someone have some ideas about how to improve the calculations related with the debt time that detekt provides, please open a discussion so we can talk about it. I do think that we need to improve that but, right now, I have no idea how.

**Pull request closed without merging**
